esphome:
  friendly_name: Jiecang Desk
  name: jiecang-desk

esp32:
  board: esp32dev
    
logger:

#wifi:
#  ssid: wifi_ssid
#  password: wifi_password
#
#api:

external_components:
  - source: components
    components: [ jiecang_desk ]

uart:
  - baud_rate: 9600
    data_bits: 8
    parity: NONE
    stop_bits: 1
    tx_pin: 18
    rx_pin: 19

jiecang_desk:

sensor:
  - platform: jiecang_desk
    name: Height
    unit_of_measurement: cm

button:
  - platform: jiecang_desk
    position_1:
      name: Position 1
    position_2:
      name: Position 2
    position_3:
      name: Position 3
    position_4:
      name: Position 4

cover:
  - platform: jiecang_desk
    name: Cover